module.exports = {
  actionFut: [
    'will help to fix',
    'will watch the (movie|game|match|tv)',
    'will banish (dresses|visits|calls|dogs)',
    'will make (friends|contacts|calls|changes)',
    'will (investigate|study|read|comment|talk) about it',
    'will (fix|ruin|improve|banish|correct) everything',
    'will complain about the (rules|salary|day|program)',
    'will be (busy|alone|isolated|rested|prepared)',
    'will eat (salad|too much|pizza|vegan foods|cookies)',
    'will read (very fast|books|magazines|comics|alone)',
    'will buy (movies|new books|fruits|cars|musics|balls)',
    'will start (studying|training|complaining|protesting)',
    'will present new (options|activities|rules|students|updates)',
    'will stop (playing games|fighting|causing trouble|screaming|complaining|talking)',
  ],
  actionPast: [
    'sold the (candle|coat|car|cookie)',
    'told me the (news|stories|rules)',
    'did the (exam|work|task|research)',
    'painted the (car|table|chair|house)',
    'studied (finance|business|music|arts)',
    'opened the (gifts|toys|boxes|cards)',
    'changed the (experiment|exercise|method)',
    'started the (search|investigation|speech)',
    'used to (run|study|read books|watch news)',
    'made new (contracts|paintings|decorations)',
    'solved your (problems|challenges|tricks|questions)',
  ],
  actionIngPos: [
    //
    'is using your (tips|tools|notes)',
    'is showing your (ideas|pictures|grades)',
    'is breaking the (pencils|tools|chairs|windows)',
    'is reading your (poems|stories|articles|activities)',
    'is practicing your (ideas|tips|lessons|instructions)',
    'is listening your (lessons|suggestion|instructions|songs)',
    'is improving your (sanity|projects|compositions|characters|grades)',
  ],
}
