module.exports = {
  action: [
    'will be busy',
    'will be alone',
    'will be isolated',
    'will eat salad',
    'will eat too much',
    'will talk about it',
    'will help to fix',
    'will read very fast',
    'will watch the movie',
    'will investigate about it',
    'will stop playing games',
    'will make friends',
    'will buy movies',
    'will buy new books',
    'will buy fruits',
    'will ban dress',
    'is fixing everything',
    'is presenting new options',
    'is complaining about the rules',
    'is starting to study',
  ],
  actionPast: [
    'bought fancy clothes',
    'bought new records',
    'studied finance',
    'did the tests',
    'solved your problems',
    'solved the difficult questions',
    'participated in the search',
    'participated in the cleaning',
    'participated in the experiment',
    'practiced as much as possible',
    'used to run',
    'used to study',
    'used to read books',
    'used to watch news',
  ],
  actionPoss: [
    //
    'is improving your health',
    'is improving your projects',
    'is hearing your speech',
    'is reading your poems',
    'is using your tips',
    'is practicing your ideas',
    'is showing your ideas',
  ],
}
