module.exports = {
  actionFut: [
    'will talk about it',
    'will help to fix',
    'will investigate about it',
    'will make friends',
    'will ban dress',
    'will fix everything',
    'will present new options',
    'will complain about the rules',
    'will start to study',
    'will be (busy|alone|isolated)',
    'will buy (movies|new books|fruits)',
    'will watch the (movie|game|match|tv)',
    'will eat (salad|too much|pizza|vegan foods)',
    'will read (very fast|books|magazines|comics)',
    'will stop (playing games|fighting|causing trouble|screaming|complaining|talking)',
  ],
  actionPast: [
    'sold the discs',
    'studied finance',
    'did the exam',
    'started the search',
    'opened the presents',
    'changed the experiment',
    'made new (contracts)',
    'told me the (news|stories|rules)',
    'painted the (car|table|chair|house)',
    'used to (run|study|read books|watch news)',
    'solved your (problems|challenges|tricks|puzzle|questions)',
  ],
  actionIngPos: [
    //
    'is improving your sanity',
    'is improving your projects',
    'is listening your lesson',
    'is reading your poems',
    'is reading your articles',
    'is using your tips',
    'is practicing your ideas',
    'is showing your ideas',
    'is breaking the pencils',
  ],
}
