module.exports = {
  introFut: [
    'from that day on',
    'guess what day',
    'after that',
    'always after that',
    'guess what time',
  ],
  introIf: ["it's not as if", 'I want to know if', 'nobody will believe if'],
  intro: [
    'but',
    'why',
    'only',
    'and why',
    'is true',
    'no doubt',
    "I'm sure",
    'actually',
    'apparently',
    'believe me',
    'I found out',
    "it's serious",
    'just because',
    "i'm sorry but",
    'being sincere',
    "I don't think",
    'i understand why',
    "it's safe to say",
    'without question',
    'now i can see why',
    'to tell the truth',
    'I (swear|believe)',
    'For the first time',
    '(probably|possibly)',
    'to be (clear|honest)',
    "I can't believe what",
    'guess close to where',
    "It's easy to see why",
    "I (will|'d) love to see",
  ],
  introPast: [
    'I knew',
    'did you know',
    'truth be told',
    'when it rained',
    'since that day',
    'Nobody knew but',
    'always before that',
    "I'd (know|notice) if",
    'however much it happened',
    'before (that|it happened)',
    'I (hated|loved|liked) when',
    'I was (worried|sad|curious) when',
    'as I (told you|explained) before',
    'as I (said|already said|warned|predicted)',
  ],

  introIng: ['i hope', "it's surprising that"],
}
