module.exports = {
  introFut: [
    'from that day on',
    'guess what when',
    'after that',
    'always after that',
  ],

  intro: [
    'but',
    'why',
    'only',
    'and why',
    'is true',
    'no doubt',
    "I'm sure",
    'actually',
    'apparently',
    'believe me',
    'I found out',
    "it's serious",
    'just because',
    "i'm sorry but",
    'being sincere',
    "I don't think",
    'i understand why',
    "it's safe to say",
    'without question',
    'now i can see why',
    'to tell the truth',
    'I (swear|believe)',
    'For the first time',
    '(probably|perhaps)',
    'to be (clear|honest)',
    "I can't believe",
    'guess (where|why)',
    "It's easy to see why",
  ],
  introPast: [
    'I knew',
    'did you know',
    'truth be told',
    'since that day',
    'Nobody knew but',
    'always before that',
    'when this happened',
    'before (that|it happened)',
    'I (hated|loved|liked) when',
    'I was (worried|sad|curious) when',
    'as I (told you|explained) before',
    'as I (said|already said|warned|predicted)',
  ],
}
