module.exports = {
  intro: [
    //
    'but',
    'why',
    'only',
    'and why',
    'is true',
    'no doubt',
    'actually',
    'apparently',
    'believe me',
    'I found out',
    'after that',
    'guess where',
    "it's serious",
    'to be clear',
    'to be honest',
    'just because',
    "i'm sorry but",
    'being sincere',
    'I swear that',
    "I'm sure that",
    'guess what day',
    'I believe that',
    "it's not as if",
    'guess what time',
    'i understand why',
    "it's safe to say",
    'without question',
    'always after that',
    'I want to know if',
    'from that day on',
    'now i can see why',
    "I don't think that",
    'to tell the truth',
    'For the first time',
    '(probably|possibly)',
    "I can't believe what",
    'guess close to where',
    "It's easy to see why",
    'nobody will believe if',
    "I (will|'d) love to see",
  ],
  introPast: [
    'I knew',
    'did you know',
    'truth be told',
    'when it rained',
    'since that day',
    'Nobody knew but',
    'always before that',
    "I'd (know|notice) if",
    'however much it happened',
    'before (that|it happened)',
    'I (hated|loved|liked) when',
    'I was (worried|sad|curious) when',
    'as I (told you|explained) before',
    'as I (said|already said|warned|predicted)',
  ],

  introIng: ['i hope', "it's surprising that"],
}
