module.exports = {
  who: [
    'he',
    'Jay',
    'Joe',
    'Roy',
    'Leo',
    'Tony',
    'Erik',
    'Gary',
    'Oliver',
    'she',
    'Zoe',
    'Ana',
    'Eve',
    'Bia',
    'Mary',
    'Vera',
    'Mara',
    'Lucy',
    'Alice',
    'my dad',
    'my wife',
    '(my|the) boss',
    'my uncle',
    'my teacher',
    'my daughter',
    'my brother',
    'your (kid|child|son)',
    'your aunt',
    'your sister',
    'your friend',
    'your director',
    'the boy',
    'the seller',
    'the writer',
    'the leader',
    'the prince',
    'the doctor',
    'the artist',
    'the manager',
  ],
}
