['who', 'what', 'where'],
  // ['who', 'whatPast', 'where'],
  // ['who', 'actionFut', 'when'],
  // ['who', 'actionFut', 'where'],
  // ['who', 'actionPast', 'whenPast'],
  // ['who', 'actionPast', 'where'],
  // ['who', 'actionPast', 'amountPast'],
  // ['who', 'actionIngPos', 'where'],
  // ['intro', 'who', 'actionFut'],
  // ['intro', 'who', 'actionIngPos'],
  // ['introPast', 'who', 'actionPast'],
  // ['intro', 'who', 'actionPres'],
  // ['intro', 'who', 'actionIng'],
  // ['who', 'actionIng', 'where'],